### ISSUE TITLE
Not working on |media files?

### ISSUE THREAD

**Issue by mpetricek** [OFFLINE-GmbH/oc-responsive-images-plugin#16] opened 2018-02-06 20:37 UTC
Hi,

the plugin is working great on every other file but not on files from  media gallery? Why is that?

Thank you!

**Comment by Alex360hd** [comment] 2018-07-04 10:06
I can confirm the issue. Never noticed it before, but all images loaded from media folder are not considered.

Could confirm that behavior on several different test and production websites.

**Comment by mpetricek** [comment] 2018-07-04 14:13
This issue seems more complex. On some projects it works but after some time.  I'm working on different project now and it doesn't work at all no matter where images are.

**Comment by Alex360hd** [comment] 2018-07-04 14:29
Yes, I just noticed the same thing. It seems that one recent update broke something as it worked well before on every project, and I checked again. All recent project are not working

**Comment by tobias-kuendig** [comment] 2018-07-04 14:31
Are you on 1.1.5?

**Comment by mpetricek** [comment] 2018-07-04 14:40
Yes I am

**Comment by Alex360hd** [comment] 2018-07-04 14:42
Same for me

**Comment by Alex360hd** [comment] 2018-07-05 07:36
Option to log unprocessable images checked, but I don't have any error in logs. I can just see that that the image doesn't have all the srcset stuff it should.

Here is some infos that could help to reproduce : 

- I use the [image resizer plugin](https://octobercms.com/plugin/toughdeveloper-imageresizer)
- I use [lazysizes ](https://github.com/aFarkas/lazysizes) for lazyloading

So, a typical image integration in my code looks like that : 

    <img class="lazyload" data-src="{{ 'dummy.jpg'|media|resize(600, 600) }}" data-sizes="auto" alt="Dummy image" />

Here is some things to notice : 

- I setup your plugin to read data-src tag instead of standard src to make it compatible with lazysizes
- this setup worked very well some times ago, then it suddenly stopped working.

**Comment by tobias-kuendig** [comment] 2018-07-05 08:06
@mpetricek any chance you use the image resizer plugin too? I can reproduce it by using it in combination with the `media` filter.

**Comment by tobias-kuendig** [comment] 2018-07-05 08:34
Is it possible that you don't have the `APP_URL` environment variable set or it doesn't match your hostname?
It looks like the environment variable was used but not the `app.url` config entry. I fixed this in 1.1.6. Does this fix the problem for you as well? Make sure the app url maches your hostname exactly.

**Comment by Alex360hd** [comment] 2018-07-05 08:40
When you say APP_URL, you mean the "url" settings in app.php in the config folder ?

**Comment by Alex360hd** [comment] 2018-07-05 08:42
I updated to 1.1.6 and set the correct url in the app.php file (still was the development url whereas the concerned website was in production).

It resolved the problem : thanks !

**Comment by tobias-kuendig** [comment] 2018-07-05 09:35
Great, thanks for testing this out. @mpetricek I bet your problem can also be solved by updating and/or fixing the app url.

**Comment by Alex360hd** [comment] 2018-07-05 09:43
And thanks to YOU for your reactivity !

**Comment by mpetricek** [comment] 2018-07-05 12:35
Yes, indeed it was wrong url in app.php. Thank you!

**Comment by Flothus** [comment] 2019-02-23 08:15
Hi, sorry to chip in again. 
I noticed that I have problems with this on a production site. 
At first this problem only occurred in production and not on not on my dev machine. 
But after updating October from 443 to 446 with responsive image the problem also appeared in dev. 

Checked the app Url as recommended but everything seems fine. Do you guys notice any problems after updating to 446?

**Comment by tobias-kuendig** [comment] 2019-02-23 08:41
I'm not aware of any problems regarding the update. 

Could you try to debug this line and see if it parses the correct path to your image files?

The `normalizeImagePath` method should return the absolute local path to your image.

https://github.com/OFFLINE-GmbH/oc-responsive-images-plugin/blob/develop/classes/ResponsiveImage.php#L260

**Comment by Flothus** [comment] 2019-02-23 10:39
Thanks for that!
So it's not related to media files at all. 
It didn't dump the path for those images and it looks like the problem is having a data attribute before the src property. 

Moving the data-attribute behind src fixed it. 
Is this something I should know or is this undesired behaviour?

**Comment by tobias-kuendig** [comment] 2019-02-23 10:44
This looks like a bug then, thanks. I'll take a look at it.

**Comment by Flothus** [comment] 2019-02-23 10:51
Thanks for the great support 👍

**Comment by tobias-kuendig** [comment] 2019-02-25 08:59
This problem has been fixed in 9141f4992cbbec3df63be656990a3271af4c3cf2 and is released as v2.0.6

Thank you for the bug report!

**Closed by tobias-kuendig** 2019-02-25 08:59 UTC
Labels: bug, help wanted
